### ISSUE TITLE
Block scope?

### ISSUE THREAD

**Issue by mgavrin** [vluzko/Grace#23]
Decide whether variables defined in a block are going to have block scope or function scope, plus any other scope-related decisions that need making.

In favor of block scope: harder to accidentally use an undefined variable.
Against block scope: type declarations not right next to the first (useful) initialization.

**Comment by vluzko** [comment]
I'd argue for block scope. Unless the function is very long it should still be relatively easy to find the type information. If the function is very long, there are probably bigger problems with the code base.
